[tools]
ruby = "latest"
"github:CppCXY/EmmyLuaCodeStyle" = { version = "latest", strip_components = 1, bin_path = "bin", filter_bins = "CodeFormat" }
"npm:lefthook" = "latest"

[hooks]
postinstall = ["lefthook install", "bundle", "rake update_neovim"]

[tasks.update_neovim]
description = "Download neovim repo"
run = ["rake update_neovim"]

[tasks.format]
description = "Format code"
run = ["CodeFormat format -d -ow ."]

[tasks.check_format]
description = "Check code format"
run = ["CodeFormat check -d ."]
