[tools]
ruby = "latest"
"github:CppCXY/EmmyLuaCodeStyle" = { version = "latest", strip_components = 1, bin_path = "bin", filter_bins = "CodeFormat" }

[tasks.update_neovim]
description = "Download neovim repo"
run = ["rake update_neovim"]

[tasks.format]
description = "Format code"
run = ["CodeFormat format -ow ."]

[tasks.check_format]
description = "Check code format"
run = ["CodeFormat check ."]
