[tools]
ruby = "latest"
stylua = "latest"

[tasks.update_neovim]
description = "Download neovim repo"
run = [
    "rake update_neovim"
]

[tasks.format]
description = "Format code"
run = [
    "stylua ."
]

[tasks.check_format]
description = "Check code format"
run = [
    "stylua --check ."
]
